import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import { cn } from "@/lib/utils";
import { ViewTransitions } from "next-view-transitions";
import { NavBar } from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body
          className={cn(
            "w-dvw min-w-dvw h-dvh min-h-dvh antialiased",
            inter.className,
          )}
        >
          <Providers>{children}</Providers>
          <NavBar />
        </body>
      </html>
    </ViewTransitions>
  );
}
